src/main/java/ru/ifmo/se/labs/asurkis/lab3/InputBean.java
package ru.ifmo.se.labs.asurkis.lab3;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.io.Serializable;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

@ManagedBean(name="input")
@ViewScoped
public class InputBean implements Serializable {
    private int userId;
    private String newUsername;
    private double x;
    private double y;
    private boolean[] rs = new boolean[5];
    private List<Query> queryList;

    {
        FacesContext context = FacesContext.getCurrentInstance();
        ModelBean modelBean = context.getApplication().evaluateExpressionGet(context, "#{model}", ModelBean.class);
        queryList = modelBean.getQueries();
    }

    public void addCurrent() {
        FacesContext context = FacesContext.getCurrentInstance();
        ModelBean modelBean = context.getApplication().evaluateExpressionGet(context, "#{model}", ModelBean.class);

        Point point = new Point(x, y);
        int queryCount = 0;
        for (int i = 0; i < rs.length; i++) {
            if (rs[i]) {
                queryCount++;
            }
        }

        int queryId = 0;
        Query[] queries = new Query[queryCount];

        for (int i = 0; i < rs.length; i++) {
            if (rs[i]) {
                queries[queryId++] = new Query(point, i + 1);
            }
        }

        modelBean.addQueries(queries);
        queryList = modelBean.getQueries();
    }

    public void addUser() {
        FacesContext context = FacesContext.getCurrentInstance();
        ModelBean modelBean = context.getApplication().evaluateExpressionGet(context, "#{model}", ModelBean.class);

        modelBean.addObjects(new User(newUsername));
    }

    public void removeUser() {
        FacesContext context = FacesContext.getCurrentInstance();
        ModelBean modelBean = context.getApplication().evaluateExpressionGet(context, "#{model}", ModelBean.class);
        modelBean.removeUser(userId);
    }

    public void updateQueries() {
        FacesContext context = FacesContext.getCurrentInstance();
        ModelBean modelBean = context.getApplication().evaluateExpressionGet(context, "#{model}", ModelBean.class);
        modelBean.updateQueries(queryList);
        queryList = modelBean.getQueries();
    }

    @Override
    public String toString() {
        return "InputBean{" +
                "username='" + newUsername + '\'' +
                ", x=" + x +
                ", y=" + y +
                ", rs=" + Arrays.toString(rs) +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        InputBean inputBean = (InputBean) o;
        return Double.compare(inputBean.x, x) == 0 &&
                Double.compare(inputBean.y, y) == 0 &&
                Objects.equals(newUsername, inputBean.newUsername) &&
                Arrays.equals(rs, inputBean.rs);
    }

    @Override
    public int hashCode() {
        int result = Objects.hash(newUsername, x, y);
        result = 31 * result + Arrays.hashCode(rs);
        return result;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        FacesContext context = FacesContext.getCurrentInstance();
        ModelBean modelBean = context.getApplication().evaluateExpressionGet(context, "#{model}", ModelBean.class);
        modelBean.setCurrentUser(userId);
        this.userId = userId;
    }

    public String getNewUsername() {
        return newUsername;
    }

    public void setNewUsername(String newUsername) {
        this.newUsername = newUsername;
    }

    public double getX() {
        return x;
    }

    public void setX(double x) {
        this.x = x;
    }

    public double getY() {
        return y;
    }

    public void setY(double y) {
        this.y = y;
    }

    public boolean[] getRs() {
        return rs;
    }

    public void setRs(boolean[] rs) {
        this.rs = rs;
    }

    public List<Query> getQueryList() {
        return queryList;
    }

    public void setQueryList(List<Query> queryList) {
        this.queryList = queryList;
    }
}

src/main/java/ru/ifmo/se/labs/asurkis/lab3/ModelBean.java
package ru.ifmo.se.labs.asurkis.lab3;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import java.io.Serializable;
import java.util.List;
import java.util.Objects;

@ManagedBean(name = "model")
@SessionScoped
public class ModelBean implements Serializable {
    private EntityManagerFactory factory = Persistence.createEntityManagerFactory("QueriesDB");
    private User currentUser;

    public void addQueries(Query... queries) {
        EntityManager manager = factory.createEntityManager();
        manager.getTransaction().begin();
        for (Query q : queries) {
            Point p = q.getPoint();
            p.setUser(currentUser);
            manager.persist(p);
            manager.persist(q);
        }
        manager.getTransaction().commit();
        manager.close();
    }

    public void updateQueries(List<Query> queryList) {
        EntityManager manager = factory.createEntityManager();
        manager.getTransaction().begin();
        for (Query query: queryList) {
            Query q = manager.find(Query.class, query.getId());
            Point p = q.getPoint();
            if (currentUser.getId() != p.getUser().getId()) {
                continue;
            }
            if (query.isToDelete()) {
                manager.remove(q);
            } else {
                q.setRadius(query.getRadius());
                manager.merge(q);
            }
        }
        manager.createQuery("DELETE FROM Point p WHERE 0=(SELECT COUNT(*) FROM Query q WHERE p=q.point)").executeUpdate();
        manager.getTransaction().commit();
        manager.close();
    }

    public void addObjects(Object... objects) {
        EntityManager manager = factory.createEntityManager();
        manager.getTransaction().begin();
        for (Object o : objects) {
            manager.persist(o);
        }
        manager.getTransaction().commit();
        manager.close();
    }

    public void removeQuery(int queryId) {
        EntityManager manager = factory.createEntityManager();
        manager.getTransaction().begin();
        manager.createQuery("DELETE FROM Query q WHERE :queryId=q.id AND :user=(SELECT p.user FROM Point p WHERE p=q.point)")
                .setParameter("queryId", queryId)
                .setParameter("user", currentUser)
                .executeUpdate();
        manager.createQuery("DELETE FROM Point p WHERE 0=(SELECT COUNT(*) FROM Query q WHERE p=q.point)").executeUpdate();

        manager.getTransaction().commit();
        manager.close();
    }

    public void removeUser(int userId) {
        EntityManager manager = factory.createEntityManager();
        manager.getTransaction().begin();
        manager.createQuery("DELETE FROM Query q WHERE :userId=(SELECT p.user.id FROM Point p WHERE p=q.point)").setParameter("userId", userId).executeUpdate();
        manager.createQuery("DELETE FROM Point p WHERE :userId=(SELECT u.id FROM User u WHERE u=p.user)").setParameter("userId", userId).executeUpdate();
        manager.createQuery("DELETE FROM User  u WHERE :userId=u.id").setParameter("userId", userId).executeUpdate();
        manager.getTransaction().commit();
        manager.close();
    }

    public void removeUser(User user) {
        EntityManager manager = factory.createEntityManager();
        manager.getTransaction().begin();
        manager.createQuery("DELETE FROM Query q WHERE :user=(SELECT p.user FROM Point p WHERE p=q.point)").setParameter("user", user).executeUpdate();
        manager.createQuery("DELETE FROM Point p WHERE :user=p.user").setParameter("user", user).executeUpdate();
        manager.remove(user);
        manager.getTransaction().commit();
        manager.close();
    }

    public void removeUnusedPoints() {
        EntityManager manager = factory.createEntityManager();
        manager.getTransaction().begin();
        manager.createQuery("DELETE FROM Point p WHERE 0=(SELECT COUNT(*) FROM Query q WHERE p=q.point)").executeUpdate();
        manager.getTransaction().commit();
        manager.close();
    }

    public User findUser(int userId) {
        EntityManager manager = factory.createEntityManager();
        User result = manager.find(User.class, userId);
        manager.close();
        return result;
    }

    public boolean userExists(String username) {
        EntityManager manager = factory.createEntityManager();
        Boolean result = manager.createQuery("SELECT COUNT(*)<>0 FROM User u where :username=u.name", Boolean.class).setParameter("username", username).getSingleResult();
        manager.close();
        return result;
    }

    public List<Point> getPoints() {
        EntityManager manager = factory.createEntityManager();
        List<Point> result = manager.createQuery(
                "SELECT p FROM Point p WHERE :user=p.user ORDER BY p.id", Point.class
        ).setParameter("user", currentUser).getResultList();
        manager.close();
        return result;
    }

    public List<Query> getQueries() {
        EntityManager manager = factory.createEntityManager();
        List<Query> result = manager.createQuery(
                "SELECT q FROM Query q WHERE :user=q.point.user ORDER BY q.id", Query.class
        ).setParameter("user", currentUser).getResultList();
        manager.close();
        return result;
    }

    public List<User> getUsers() {
        EntityManager manager = factory.createEntityManager();
        List<User> result = manager.createQuery("SELECT u FROM User u ORDER BY u.id", User.class).getResultList();
        manager.close();
        return result;
    }

    public User getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(int userId) {
        setCurrentUser(findUser(userId));
    }

    public void setCurrentUser(User currentUser) {
        this.currentUser = currentUser;
    }
}

src/main/java/ru/ifmo/se/labs/asurkis/lab3/PictureBean.java
package ru.ifmo.se.labs.asurkis.lab3;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.io.Serializable;

@ManagedBean(name="picture")
@ViewScoped
public class PictureBean implements Serializable {
    public String pointStyle(Point point, InputBean inputBean) {
        int radiusCount = 0;
        int matchCount = 0;
        for (int r = 1; r <= 5; r++) {
            if (inputBean.getRs()[r - 1]) {
                radiusCount++;
                if (point.fallsInto(r)) {
                    matchCount++;
                }
            }
        }
        return pointStyleByCount(radiusCount, matchCount);
    }

    public int getRadiusCount() {
        FacesContext context = FacesContext.getCurrentInstance();
        InputBean inputBean = context.getApplication().evaluateExpressionGet(context, "#{input}", InputBean.class);

        int result = 0;
        for (int i = 0; i < 5; i++) {
            if (inputBean.getRs()[i])
                result++;
        }
        return result;
    }

    public String pointStyleByCount(int radiusCount, int matchCount) {
        if (radiusCount == 0) {
            return "stroke: #000; fill: #888";
        }

        double a = (double) matchCount / radiusCount;
        double r = 255 * Math.sqrt(1 - a);
        double g = 255 * Math.sqrt(a);
        double b = 0;
        int ri = (int) r;
        int gi = (int) g;
        int bi = (int) b;

        return String.format("stroke: #000; fill: rgb(%d, %d, %d)", ri, gi, bi);
    }
}

src/main/webapp/main.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <h:outputStylesheet library="css" name="styles.css"/>
    <h:outputScript library="js" name="main.js"/>
</h:head>

<h:body>
    <div>
        Текущий пользователь: #{model.currentUser.name}
    </div>

    <h:form id="inputForm">
        <table>
            <tr>
                <td> X: </td>
                <td>
                    <h:selectOneMenu value="#{input.x}">
                        <f:selectItem itemValue="-5" itemLabel="-5"/>
                        <f:selectItem itemValue="-4" itemLabel="-4"/>
                        <f:selectItem itemValue="-3" itemLabel="-3"/>
                        <f:selectItem itemValue="-2" itemLabel="-2"/>
                        <f:selectItem itemValue="-1" itemLabel="-1"/>
                        <f:selectItem itemValue="0" itemLabel="0"/>
                        <f:selectItem itemValue="1" itemLabel="1"/>
                        <f:selectItem itemValue="2" itemLabel="2"/>
                        <f:selectItem itemValue="3" itemLabel="3"/>
                    </h:selectOneMenu>
                </td>
                <td/>
            </tr>

            <tr>
                <td> Y: </td>
                <td>
                    <h:inputText id="inputY" value="#{input.y}" autocomplete="off" validatorMessage="Введите число от -3 до 5">
                        <f:validateDoubleRange minimum="-3.0" maximum="5.0"/>
                    </h:inputText>
                </td>
                <td><h:message for="inputY" style="color: red"/></td>
            </tr>

            <tr>
                <td> R: </td>
                <td>
                    <div>
                        <h:selectBooleanCheckbox id="r1" value="#{input.rs[0]}">
                            <f:ajax execute="r1" render="pictureForm"/>
                        </h:selectBooleanCheckbox>
                        <h:outputLabel for="r1"> 1 </h:outputLabel>
                    </div>
                    <div>
                        <h:selectBooleanCheckbox id="r2" value="#{input.rs[1]}">
                            <f:ajax execute="r2" render="pictureForm"/>
                        </h:selectBooleanCheckbox>
                        <h:outputLabel for="r2"> 2 </h:outputLabel>
                    </div>
                    <div>
                        <h:selectBooleanCheckbox id="r3" value="#{input.rs[2]}">
                            <f:ajax execute="r3" render="pictureForm"/>
                        </h:selectBooleanCheckbox>
                        <h:outputLabel for="r3"> 3 </h:outputLabel>
                    </div>
                    <div>
                        <h:selectBooleanCheckbox id="r4" value="#{input.rs[3]}">
                            <f:ajax execute="r4" render="pictureForm"/>
                        </h:selectBooleanCheckbox>
                        <h:outputLabel for="r4"> 4 </h:outputLabel>
                    </div>
                    <div>
                        <h:selectBooleanCheckbox id="r5" value="#{input.rs[4]}">
                            <f:ajax execute="r5" render="pictureForm"/>
                        </h:selectBooleanCheckbox>
                        <h:outputLabel for="r5"> 5 </h:outputLabel>
                    </div>
                </td>
                <td/>
            </tr>

            <tr>
                <td colspan="3">
                    <h:commandButton action="#{input.addCurrent()}" value="Проверить"/>
                </td>
            </tr>
        </table>
        <h:commandLink action="page" value="Назад"/>
    </h:form>

    <h:form id="tableForm">
        <h:dataTable var="query" value="#{input.queryList}"
                     styleClass="resultsTable"
                     headerClass="resultsTableHeader"
                     rowClasses="resultsTableOddRow,resultsTableEvenRow">
            <h:column>
                <f:facet name="header"> Удалить? </f:facet>
                <h:selectBooleanCheckbox value="#{query.toDelete}"/>
            </h:column>
            <h:column>
                <f:facet name="header"> X </f:facet>
                #{query.point.x}
            </h:column>
            <h:column>
                <f:facet name="header"> Y </f:facet>
                #{query.point.y}
            </h:column>
            <h:column>
                <f:facet name="header"> R </f:facet>
                <h:inputText id="inputR#{query.id}" value="#{query.radius}" autocomplete="off" validatorMessage="Введите число от 0 до 5">
                    <f:validateDoubleRange minimum="0.0" maximum="5.0"/>
                </h:inputText>
            </h:column>
            <h:column>
                <f:facet name="header"> Попадает </f:facet>
                #{query.result ? "Да" : "Нет"}
            </h:column>
            <h:column>
                <h:message for="inputR#{query.id}" style="color: red"/>
            </h:column>
        </h:dataTable>
        <h:commandButton action="#{input.updateQueries()}" value="Обновить"/>
    </h:form>

    <h:form id="pictureForm">
        <!--
            При попытке разместить картинку слева происходит какая-то людая жесть
            Не применяются стили, разные формы объединяются в одну и т.д.
            Поэтому в этот раз картинка будет справа
        -->
        <h:inputText id="svgInputX" value="#{input.x}">
            <f:validateDoubleRange minimum="-5.0" maximum="3.0"/>
        </h:inputText>
        <h:inputText id="svgInputY" value="#{input.y}">
            <f:validateDoubleRange minimum="-3.0" maximum="5.0"/>
        </h:inputText>
        <h:commandButton id="checkButton" action="#{input.addCurrent()}" value="Проверить"/>

        <svg xmlns="http://www.w3.org/2000/svg"
             xmlns:c="http://java.sun.com/jsp/jstl/core"
             width="600" height="600"
             onclick="onPictureClick">
            <!--
                Т.к. <c:if> и <c:forEach> вместе отрабатывают с ошибкой,
                (внутри условия внутри цикла значение переменной цикла непредсказуемо меняется)
                а писать сервлет и вставку без экранирования ещё менее красиво,
                то я решил развернуть цикл. По-хорошему вот это делается проще
            -->
            <c:if test="#{input.rs[4]}">
                <path id="r5-path" d="M300 50 A250 250 0 0 1 550 300 L425 300 L300 425 L300 300 L50 300 L50 175 L300 175 Z"/>
            </c:if>
            <c:if test="#{input.rs[3]}">
                <path id="r4-path" d="M300 100 A200 200 0 0 1 500 300 L400 300 L300 400 L300 300 L100 300 L100 200 L300 200 Z"/>
            </c:if>
            <c:if test="#{input.rs[2]}">
                <path id="r3-path" d="M300 150 A150 150 0 0 1 450 300 L375 300 L300 375 L300 300 L150 300 L150 225 L300 225 Z"/>
            </c:if>
            <c:if test="#{input.rs[1]}">
                <path id="r2-path" d="M300 200 A100 100 0 0 1 400 300 L350 300 L300 350 L300 300 L200 300 L200 250 L300 250 Z"/>
            </c:if>
            <c:if test="#{input.rs[0]}">
                <path id="r1-path" d="M300 250 A50 50 0 0 1 350 300 L325 300 L300 325 L300 300 L250 300 L250 275 L300 275 Z"/>
            </c:if>

            <line x1="300" y1="10" x2="300" y2="600"/>
            <line x1="0" y1="300" x2="590" y2="300"/>
            <polygon points="300 0 295 10 305 10"/>
            <polygon points="600 300 590 295 590 305"/>
            <text x="290" y="10" text-anchor="end"> y </text>
            <text x="595" y="290" text-anchor="end"> x </text>

            <c:forEach var="i" begin="0" end="5">
                <circle cx="${300+50*i}" cy="300" r="3"/>
                <text x="${296+50*i}" y="296" text-anchor="end"> ${i} </text>
                <c:if test="${i != 0}">
                    <circle cx="${300-50*i}" cy="300" r="3"/>
                    <text x="${296-50*i}" y="296" text-anchor="end"> ${-i} </text>
                    <circle cx="300" cy="${300-50*i}" r="3"/>
                    <text x="296" y="${296-50*i}" text-anchor="end"> ${i} </text>
                    <circle cx="300" cy="${300+50*i}" r="3"/>
                    <text x="296" y="${296+50*i}" text-anchor="end"> ${-i} </text>
                </c:if>
            </c:forEach>

            <c:forEach var="point" items="#{model.points}">
                <circle cx="#{300+50*point.x}" cy="#{300-50*point.y}" r="5" style="#{picture.pointStyle(point, input)}"/>
            </c:forEach>

            <c:choose>
                <c:when test="#{picture.radiusCount != 0}">
                <c:forEach var="i" begin="0" end="#{picture.radiusCount}">
                    <circle cx="12" cy="#{24 * i + 12}" r="5"
                            style="#{picture.pointStyleByCount(picture.radiusCount, i)}"/>
                    <text x="24" y="#{24 * i + 18}"> Попадает в #{i} радиус(ов) </text>
                </c:forEach>
                </c:when>
                <c:otherwise>
                    <circle cx="12" cy="12" r="5" style="#{picture.pointStyleByCount(0, 0)}"/>
                    <text x="24" y="18"> Радиусы не заданы </text>
                </c:otherwise>
            </c:choose>
        </svg>
    </h:form>
</h:body>
</html>

src/main/webapp/welcome.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <style>
        .ui-analog-clock {
            width: 200px;
        }
    </style>
</h:head>

<h:body>
    <div>
        <div>Студент: Суркис Антон Игоревич</div>
        <div>Группа: P3213</div>
        <div>Вариант: 213905</div>
    </div>

    <br/>

    <h:form>
        <div>Добавить пользователя:</div>
        <div><h:message for="newUserName" style="color: red"/></div>
        <div>
            <h:inputText id="newUserName" value="#{input.newUsername}" validatorMessage="Введите новое имя пользователя">
                <f:validator validatorId="ru.ifmo.se.labs.asurkis.lab3.UsernameValidator"/>
            </h:inputText>
            <h:commandButton action="#{input.addUser()}" value="Добавить"/>
        </div>
    </h:form>

    <br/>

    <h:form>
        <p:clock mode="server" displayMode="analog"/>
        <br/>
        <div>Пользователь:</div>
        <div><h:message for="userSelect" style="color: red"/></div>
        <div>
            <h:selectOneMenu id="userSelect" value="#{input.userId}" required="true" requiredMessage="Выберите пользователя">
                <f:selectItem itemLabel="Выберите пользователя" itemValue="#{null}" noSelectionOption="true"/>
                <f:selectItems var="user" value="#{model.users}" itemValue="#{user.id}" itemLabel="#{user.name}"/>
            </h:selectOneMenu>
            <h:commandButton action="#{input.removeUser()}" value="Удалить"/>
        </div>
        <h:commandLink action="page" value="К основной странице"/>
    </h:form>
</h:body>
</html>